#
# Copyright (C) 2013-2016 Zakume
# Copyright (C) 2020~     Re
#
# https://game.naruto.re
#

name = 'Dogs'

[Idle]
frame = [
    'Dogs_Idle_01',
]

[NAttack]
type = 'aAttack'
value = 2460
rangeX = 0
rangeY = 48

frame = [
    'setCmd = findTarget',
    'setCmd = setTransport',
    'Dogs_Nattack_01',
    'Dogs_Nattack_02',
    'Dogs_Nattack_03',
    'Dogs_Nattack_04',
    'setHit = c_hit',
    'setDelay = 30',
    'setDestroy = 0',
]
