#
# Copyright (C) 2013-2016 Zakume
# Copyright (C) 2020~     Re
#
# https://game.naruto.re
#

name = 'FakeShino'
speed = 224

[Idle]
frame = [
    'Shino_Idle_001',
    'Shino_Idle_002',
    'Shino_Idle_003',
    'Shino_Idle_004',
]

[Walk]
frame = [
    'Shino_Walk_01',
    'Shino_Walk_02',
    'Shino_Walk_03',
    'Shino_Walk_04',
    'Shino_Walk_05',
    'Shino_Walk_06',
]

[NAttack]
type = 'aAttack'
value = 760
rangeX = 15
rangeY = 48

frame = [
    'BugClone_Move_001',
    'setSound = Audio/Shino/Shino_skill2_1.ogg',
    'setHit = s_hit',
    'BugClone_Move_002',
    'BugClone_Move_003',
    'setHit = s_hit',
    'BugClone_Move_004',
    'setDestroy = 0',
]
