#
# Copyright (C) 2013-2016 Zakume
# Copyright (C) 2020~     Re
#
# https://game.naruto.re
#

name = 'Kage'

[Idle]
frame = [
    'Kage_Move_01',
]

[Dead]
frame = [
    'Kage_Dead_01',
    'Kage_Dead_02',
    'Kage_Dead_03',
]

[NAttack]
type = 'aAttack'
rangeX = 32
rangeY = 32

frame = [
    'Kage_Move_01',
    'Kage_Move_02',
    'Kage_Move_03',
    'Kage_Move_04',
    'setDestroy = 0',
]
