#
# Copyright (C) 2013-2016 Zakume
# Copyright (C) 2020~     Re
#
# https://game.naruto.re
#

name = 'KageHand'

[Idle]
frame = [
    'KageHand_Move_01',
]

[Dead]
frame = [
    'KageHand_Move_02',
    'KageHand_Move_01',
]

[NAttack]
type = 'aAttack'
value = 1963
rangeX = 16
rangeY = 48

frame = [
    'KageHand_Move_01',
    'KageHand_Move_02',
    'KageHand_Move_03',
    'setHit = ct_hit',
    'setDelay = 20',
    'setDestroy = 0',
]
