#
# Copyright (C) 2013-2016 Zakume
# Copyright (C) 2020~     Re
#
# https://game.naruto.re
#

name = 'Traps'

[Idle]
frame = [
    'Traps_Move_001',
    'Traps_Move_002',
    'Traps_Move_003',
    'Traps_Move_004',
    'Traps_Move_005',
    'Traps_Move_006',
    'Traps_Move_007',
    'Traps_Move_008',
]

[NAttack]
type = 'aAttack'
value = 1960
rangeX = 32
rangeY = 48

frame = [
    'setSound = Audio/Effect/poof.ogg',
    'Traps_Attack_002',
    'Traps_Attack_003',
    'Traps_Attack_004',
    'setHit = b_hit',
    'Traps_Attack_005',
    'setDelay = 20',
    'setDestroy = 0',
]
