#
# Copyright (C) 2013-2016 Zakume
# Copyright (C) 2020~     Re
#
# https://game.naruto.re
#

name = 'Tuji2'

[Idle]
frame = [
    'Tuji2_Move_001',
]

[NAttack]
type = 'aAttack'
value = 460
rangeX = 16
rangeY = 48

frame = [
    'Tuji2_Move_001',
    'setHit = b_hit',
    'setDSound = Audio/Effect/stick_damage.ogg',
    'setDelay = 10',
    'Tuji2_Move_002',
    'setHit = b_hit',
    'setDSound = Audio/Effect/stick_damage.ogg',
    'setDelay = 10',
    'Tuji2_Move_003',
    'setHit = b_hit',
    'Tuji2_Move_004',
    'setDestroy = 0',
]
