#
# Copyright (C) 2013-2016 Zakume
# Copyright (C) 2020~     Re
#
# https://game.naruto.re
#

name = 'WaterBom'

[Idle]
frame = [
    'WaterBom_Move_01',
]

[NAttack]
type = 'aAttack'
value = 360
rangeX = 16
rangeY = 48

frame = [
    'WaterBom_Move_01',
    'setHit = c_hit',
    'WaterBom_Move_02',
    'setHit = c_hit',
    'WaterBom_Move_03',
    'setHit = c_hit',
    'WaterBom_Move_04',
    'setHit = c_hit',
    'WaterBom_Move_05',
    'setHit = c_hit',
    'WaterBom_Move_06',
    'setHit = c_hit',
    'WaterBom_Move_07',
    'setDestroy = 0',
]
