#
# Copyright (C) 2013-2016 Zakume
# Copyright (C) 2020~     Re
#
# https://game.naruto.re
#

name = 'Yominuma'

[Idle]
frame = [
    'Yominuma_Move_01',
]

[NAttack]
type = 'aAttack'
value = 260
rangeX = 0
rangeY = 48

frame = [
    'setCmd = findTarget',
    'setCmd = setTransport',
    'Yominuma_Move_01',
    'setHit = s_hit',
    'setDelay = 20',
    'Yominuma_Move_01',
    'setHit = s_hit',
    'setDelay = 20',
    'Yominuma_Move_01',
    'setHit = s_hit',
    'setDelay = 20',
    'Yominuma_Move_01',
    'setHit = s_hit',
    'setDelay = 20',
    'Yominuma_Move_01',
    'setHit = s_hit',
    'setDelay = 20',
    'Yominuma_Move_01',
    'setHit = s_hit',
    'setDelay = 20',
    'Yominuma_Move_01',
    'setHit = s_hit',
    'setDelay = 20',
    'Yominuma_Move_01',
    'setHit = s_hit',
    'setDelay = 20',
    'Yominuma_Move_01',
    'setHit = s_hit',
    'setDelay = 20',
    'Yominuma_Move_01',
    'setHit = s_hit',
    'setDelay = 20',
    'setDestroy = 0',
]
