#
# Copyright (C) 2013-2016 Zakume
# Copyright (C) 2020~     Re
#
# https://game.naruto.re
#

name = 'Sanshouuo'
hp = 8000
hpBar.y = 75
speed = 224

[Idle]
frame = [
    'Sanshouuo_Move_01',
]

[Walk]
frame = [
    'Sanshouuo_Move_01',
    'setDelay = 10',
    'Sanshouuo_Move_02',
    'setDelay = 10',
    'Sanshouuo_Move_03',
    'setDelay = 10',
]

[Hurt]
frame = [
    'setMove = 32',
    'Sanshouuo_Move_01',
]

[AirHurt]
frame = [
    'Sanshouuo_Move_01',
]

[Knockdown]
frame = [
    'Sanshouuo_Move_01',
    'setDelay = 10',
    'Sanshouuo_Move_01',
    'Sanshouuo_Move_01',
    'setDelay = 60',
    'Sanshouuo_Move_01',
]

[Float]
frame = [
    'Sanshouuo_Move_01',
    'setDelay = 10',
    'Sanshouuo_Move_01',
    'setDelay = 10',
    'Sanshouuo_Move_01',
]

[Dead]
frame = [
    'Sanshouuo_Move_01',
    'Sanshouuo_Move_01',
]

[NAttack]
type = 'aAttack'
rangeX = 16
rangeY = 48

frame = [
    'Sanshouuo_Move_01',
    'setHit = n_hit',
    'setDelay = 40',
    'Sanshouuo_Move_02',
    'setHit = n_hit',
    'setDelay = 40',
    'Sanshouuo_Move_03',
    'setHit = n_hit',
    'setDelay = 40',
]

[Skill01]
type = 'cAttack'
value = 460
rangeX = 0
rangeY = 48
cd = 15

frame = [
    'Sanshouuo_Move_04',
    'setHit = a_hit',
    'setDelay = 10',
    'Sanshouuo_Move_05',
    'setHit = a_hit',
    'setDelay = 10',
    'Sanshouuo_Move_06',
    'setHit = a_hit',
    'setDelay = 10',
    'Sanshouuo_Move_07',
    'setHit = a_hit',
    'setDelay = 10',
    'Sanshouuo_Move_08',
    'setHit = a_hit',
    'setDelay = 10',
    'Sanshouuo_Move_09',
    'setHit = a_hit',
    'setDelay = 10',
]
