#
# Copyright (C) 2013-2016 Zakume
# Copyright (C) 2020~     Re
#
# https://game.naruto.re
#

name = 'FlyKnife'

[Idle]
frame = [
    'FlyKnife_Move_01',
]

[NAttack]
type = 'aAttack'
value = 260
rangeX = 32
rangeY = 0
anim = {loop = true}
frame = [
    'FlyKnife_Move_01',
    'setHit = bl_hit',
]
