#
# Copyright (C) 2013-2016 Zakume
# Copyright (C) 2020~     Re
#
# https://game.naruto.re
#

name = 'InnerTower'
hp = 80000
hpBar.y = 100

[Idle]
frame = [
    'htower',
]

[Dead]
frame = [
    'htower',
]
