#
# Copyright (C) 2013-2016 Zakume
# Copyright (C) 2020~     Re
#
# https://game.naruto.re
#

name = 'Shino'
hp = 5000
hpBar.y = 78
speed = 224

[Idle]
frame = [
    'Shino_Idle_001',
    'Shino_Idle_002',
    'Shino_Idle_003',
    'Shino_Idle_004',
]

[Walk]
frame = [
    'Shino_Walk_01',
    'Shino_Walk_02',
    'Shino_Walk_03',
    'Shino_Walk_04',
    'Shino_Walk_05',
    'Shino_Walk_06',
]

[Hurt]
frame = [
    'setMove = 32',
    'Shino_Hurt_01',
    'Shino_Hurt_02',
    'setSound = Audio/Shino/Shino_hurt.ogg',
]

[AirHurt]
frame = [
    'Shino_AirHurt_001',
]

[Knockdown]
frame = [
    'Shino_Knockdown_001',
    'setDelay = 10',
    'Shino_Knockdown_002',
    'setDelay = 60',
    'Shino_Knockdown_003',
    'Shino_Knockdown_004',
    'Shino_Knockdown_005',
]

[Float]
frame = [
    'Shino_Float_001',
    'setDelay = 10',
    'Shino_Float_002',
    'setDelay = 10',
    'Shino_Float_003',
]

[Dead]
frame = [
    'Shino_Knockdown_001',
    'Shino_Knockdown_002',
    'setSound = Audio/Shino/Shino_dead.ogg',
]

[NAttack]
type = 'nAttack'
value = 60
rangeX = 16
rangeY = 48

frame = [
    'Shino_NAttack_001',
    'Shino_NAttack_002',
    'Shino_NAttack_003',
    'setHit = n_hit',
    'setSound = Audio/Effect/combo1.ogg',
    'Shino_NAttack_004',
    'Shino_NAttack_005',
    'Shino_NAttack_006',
    'Shino_NAttack_007',
    'setHit = n_hit',
    'setDelay = 10',
    'Shino_NAttack_008',
    'Shino_NAttack_009',
    'setSound = Audio/Effect/combo2.ogg',
    'Shino_NAttack_010',
    'setSound = Audio/Shino/Shino_combo.ogg',
    'setMove = 16',
    'Shino_NAttack_011',
    'Shino_NAttack_012',
    'setHit = l_hit',
    'setSound = Audio/Effect/combo3.ogg',
    'setDelay = 10',
]

[Skill01]
type = 'cBuff'
rangeX = 0
rangeY = 6
cd = 15

frame = [
    'setSound = Audio/Shino/Shino_skill1.ogg',
    'Shino_Skill01_001',
    'Shino_Skill01_002',
    'Shino_Skill01_003',
    'setDelay = 10',
    'Shino_Skill01_002',
    'Shino_Skill01_001',
    'setBuff = 17',
]

[Skill02]
type = 'Summon'
cd = 15
combatPoint = 1520

frame = [
    'setSound = Audio/Shino/Shino_skill2.ogg',
    'Shino_Skill02_001',
    'Shino_Skill02_002',
    'setMon = FakeShino',
    'setDelay = 20',
]

[Skill03]
type = 'Summon'
cd = 25
combatPoint = 1840

frame = [
    'setSound = Audio/Shino/Shino_skill3.ogg',
    'Shino_Skill03_001',
    'setMon = BugPillar',
    'Shino_Skill03_002',
    'Shino_Skill03_003',
    'Shino_Skill03_004',
    'setDelay = 20',
]

[Skill04]
type = 'aAttack'
value = 760
rangeX = 0
rangeY = 48
combatPoint = 3040

frame = [
    'setSound = Audio/Effect/ougis.ogg',
    'Shino_Skill05_001',
    'setSound = Audio/Shino/Shino_skill4.ogg',
    'Shino_Skill05_002',
    'Shino_Skill05_003',
    'setHit = s_hit',
    'setDSound = Audio/Effect/damage_l.ogg',
    'Shino_Skill05_004',
    'Shino_Skill05_005',
    'setHit = s_hit',
    'setDSound = Audio/Effect/damage_l.ogg',
    'Shino_Skill05_006',
    'Shino_Skill05_007',
    'setHit = s_hit',
    'setDSound = Audio/Effect/damage_l.ogg',
    'Shino_Skill05_008',
    'Shino_Skill05_009',
    'setHit = f_hit',
    'setDSound = Audio/Effect/damage_h.ogg',
    'Shino_Skill05_010',
    'Shino_Skill05_011',
    'Shino_Skill05_012',
    'setDelay = 20',
]

[Skill05]
type = 'Summon'
combatPoint = 8600

frame = [
    'setCmd = setInvincible',
    'Shino_Skill04_001',
    'setOugis = 10',
    'Shino_Skill04_002',
    'setMon = BugTomado',
    'setSound = Audio/Shino/Shino_skill5.ogg',
    'setDelay = 20',
    'setCmd = reInvincible',
]

[Spc01]
type = 'Summon'
value = 660
rangeX = 16
rangeY = 32
cd = 10
anim = {base = 'NAttack'}
frame = [
    'Shino_Skill10_003',
    'Shino_Skill10_001',
    'Shino_Skill10_002',
    'setMon = Bug',
    'setSound = Audio/Shino/Shino_skill1_1.ogg',
    'setDelay = 10',
]
